export const Path = {
  home: "/",
  friends: "/friends",
  messages: "/messages",
  clubs: "/clubs",
  register: "/register",
  search: "/search",
  login: "/login",
  schedule: "/schedule",
  events: "/events",
  photo: "/photo",
  video: "/video",
  music: "/music",
  files: "/files",
  settings: "/settings",
} as const;
